#!/usr/bin/env bash

# Variables
green='\033[1;32m'
yellow='\033[1;33m'
nocolor='\033[0m'
dotfiles=`find . -type f -name ".*"`
homedir=${HOME}"/"
dir=$(pwd)

# Functions
function log() {
    echo -e "${green}${@}${nocolor}"
}

function warning() {
    echo -e "${yellow}${@}${nocolor}"
}

function installcask() {
    echo "foo"
    #brew cask install "${@}" 2> /dev/null
}

# Start Magic
if test ! $(which brew); then
    log "Installing Brew ✈ ✈ ✈"
    ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
else 
    warning "Brew already installed"
fi

log "Updating Brew ✈ ✈ ✈"
brew update
brew upgrade

log "Installing Brew Binaries ✈ ✈ ✈"
brew install wget --enable-iri
brew install ack
brew install git
brew install node
brew install colordiff
brew install htop-osx
brew install ncdu
brew install phantomjs

log "Installing Brew Cask ✈ ✈ ✈"
brew tap phinze/homebrew-cask
brew install brew-cask

log "Cask OSX Software ✈ ✈ ✈"
installcask adium
installcask dropbox
installcask evernote
installcask expan-drive
installcask google-chrome
installcask firefox
installcask imagealpha
installcask imageoptim
installcask iterm2
installcask sublime-text
installcask skype
installcask the-unarchiver
installcask vlc

log "Cleanup Brew ✈ ✈ ✈"
brew cleanup

log "Installing Global NPM Packages ✈ ✈ ✈"
npm install grunt grunt-cli jshint node-dev -g

log "Checking for ZSH ✈ ✈ ✈"

if [ -d ~/.oh-my-zsh ]; then
    warning "You already have Oh My Zsh installed."
else
    log "Installing ZSH ✈ ✈ ✈"
    git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
    chsh -s `which zsh`
    /usr/bin/env zsh
fi

log "Copying [dot]files ✈ ✈ ✈"

mkdir -p ~/dotfiles_old

for file in $dotfiles; do
    file=${file//.\/}
    if [ -f $homedir$file ]; then
        warning "Backup $file ~ to ~/dotfiles_old"
        mv ~/$file ~/dotfiles_old/
    fi
    log "Linking $file to ~"
    ln -s $dir/$file ~/$file
done

# Remove functions
unset log
unset warning
unset installcask